with temp as(
SELECT PARENT_ID, COUNT(*) AS COUNT_CHILD
FROM ECOLI_DATA
WHERE PARENT_ID IS NOT NULL
GROUP BY PARENT_ID
),
agg as(
SELECT ID, temp.COUNT_CHILD AS CHILD_COUNT
FROM ECOLI_DATA
LEFT JOIN temp
ON ECOLI_DATA.ID = temp.PARENT_ID
)
SELECT ID, IFNULL(CHILD_COUNT,0) AS CHILD_COUNT
FROM agg