SELECT USER_ID,
NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
CONCAT(LEFT(TLNO,3),'-', SUBSTR(TLNO,4,4),'-',RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_BOARD A
LEFT JOIN USED_GOODS_USER B ON A.WRITER_ID=B.USER_ID
GROUP BY USER_ID
HAVING COUNT(*)>2
ORDER BY USER_ID DESC