SELECT REST_REVIEW.REST_ID, REST_NAME, FOOD_TYPE, REST_INFO.FAVORITES, ADDRESS, 
        ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW
JOIN REST_INFO ON REST_REVIEW.REST_ID = REST_INFO.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, REST_INFO.FAVORITES DESC
