WITH A AS (
  SELECT fish_type, COUNT(*) AS FISH_COUNT
  FROM fish_info 
  GROUP BY fish_type
)

SELECT A.FISH_COUNT, FISH_NAME_INFO.FISH_NAME
FROM A 
LEFT JOIN FISH_NAME_INFO ON A.fish_type = FISH_NAME_INFO.fish_type
ORDER BY FISH_COUNT DESC;

