/*
SELECT HISTORY_ID, -- AS "FEE"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 2 
    LEFT JOIN CAR_RENTAL_COMPANY_CAR 1 ON 2.CAR_ID = 1.CAR_ID 
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN 3 ON 2.CAR_TYPE = 3.CAR_TYPE
WHERE 1.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC
*/

SELECT HISTORY_ID,
       IF (DISCOUNT_RATE IS NULL, ROUND(DAYS*DAILY_FEE),
       ROUND(DAYS * DAILY_FEE * (1-DISCOUNT_RATE/100),0)) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
RIGHT JOIN (
SELECT HISTORY_ID, A.CAR_ID, B.CAR_TYPE, DAILY_FEE,
        DATEDIFF(END_DATE, START_DATE)+1 AS "DAYS",
        CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN "90일 이상" 
             WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN "30일 이상"
             WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7  THEN "7일 이상"
             ELSE "이 외" END AS "DURATION"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
WHERE CAR_TYPE = '트럭') D
ON D.DURATION = C.DURATION_TYPE AND D.CAR_TYPE = C.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC


-- SELECT DISCOUNT_RATE
-- FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
-- WHERE CAR_TYPE = "트럭" AND DURATION_TYPE = "7일 이상"