WITH RECURSIVE A AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM A
    WHERE HOUR < 23 
)
SELECT A.HOUR, IFNULL(B.COUNT, 0) AS COUNT
FROM A
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
           FROM ANIMAL_OUTS
           GROUP BY HOUR
           ORDER BY HOUR) B
ON A.HOUR = B.HOUR