WITH SCORE_AGG AS (
SELECT SUM(SCORE) AS SCORE, EMP_NO
FROM HR_GRADE
GROUP BY EMP_NO
)
SELECT SCORE, SCORE_AGG.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM SCORE_AGG
LEFT JOIN HR_EMPLOYEES
ON SCORE_AGG.EMP_NO = HR_EMPLOYEES.EMP_NO
WHERE SCORE = (SELECT MAX(SCORE) FROM SCORE_AGG)