SELECT 
    MAX(HR_DEPARTMENT.DEPT_ID) AS DEPT_ID, 
    MAX(HR_DEPARTMENT.DEPT_NAME_EN) AS DEPT_NAME_EN, 
    ROUND(AVG(SAL)) AS AVG_SAL
FROM HR_EMPLOYEES
LEFT JOIN HR_DEPARTMENT ON HR_DEPARTMENT.DEPT_ID = HR_EMPLOYEES.DEPT_ID
GROUP BY HR_EMPLOYEES.DEPT_ID
ORDER BY AVG(SAL) DESC